dico = {
    [
        {'description': None,
         'localisation': 'f. 1v-120v',
         'date': 'entre 981 et 1020',
         'contenu': [
             (4, 'Conlatio cum Maximino Arrianorum episcopo'),
             (4, 'Contra Maximinum haereticum Arianorum episcopum'),
             (4, 'Quatre-vingt trois questions différentes'),
             (4, 'De fide et symbolo'),
             (4, 'De Genesi contra Manichaeos'),
             (4, 'Adversus haereses'),
             (4, 'Collatio cum Pascentio ariano'),
             (5, 'De fide contra Manichaeos'),
             (7, 'Ad Trasimundum'),
             (8, 'Moralia in Job')]},
        {'description': 'Ecriture régulière de la première moitié du XIe siècle (Dufour, BSM)',
         'localisation': 'f. 121-173',
         'date': 'entre 1001 et 1050',
         'contenu': [
             (2, 'De officiis ministrorum'),
             (3, 'De conflictu vitiorum et virtutum'),
             (4, 'Sermones'),
             (4, 'Quatre-vingt trois questions différentes'),
             (6, 'Sermones'),
             (9, 'De vitiis et virtutibus'),
             (10, 'De corpore et sanguine Domini')]},
        {'description': None, 
         'localisation': 'f. 174-175',
         'date': 'entre 1100 et 1120',
         'contenu': [
             (8, 'Decreta')]},
        {'description': None,
         'localisation': 'f. 122-123',
         'date': 'entre 1131 et 1170',
         'contenu': []}]}